#:schema ../schemas/cv-schema.toml

[config]
default_language = "es"

[shared]
[shared.styles.fonts]
base = ["Geist"]
mono = ["Geist Mono"]
section_title = ["Geist"]
terminal = ["Geist Mono"]

[shared.styles.sizes]
header_name = "25pt"
header_position = "12pt"
normal = "10.5pt"
item_h1 = "11pt"
item_h2 = "9.5pt"
item_h3 = "8.5pt"
section_title = "9pt"
tag = "8.5pt"

[shared.styles.colors]
background = "#FFFFFF"
primary = "#23566B"
secondary = "#59636D"
accent = "#23566B"
text = "#242C33"
muted = "#DCE3E7"
header_bg = "#FFFFFF"
header_text = "#242C33"
header_dim = "#59636D"
terminal_text = "#23566B"
section_title = "#23566B"

[shared.styles.colors.categories]
frontend = "#23566B"
backend = "#23566B"
tools = "#23566B"
gamedev = "#23566B"
